package eu.uberdust.pcmonitor.jobs.unix.disabled;

import eu.uberdust.communication.protobuf.Message;
import eu.uberdust.pcmonitor.PcMonitor;
import eu.uberdust.pcmonitor.jobs.AbstractJob;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

/**
 * Created by IntelliJ IDEA.
 * User: amaxilatis
 * Date: 3/26/12
 * Time: 9:22 PM
 */
public class ScreenStatus extends AbstractJob {
    /**
     * LOGGER.
     */
    private static final org.apache.log4j.Logger LOGGER = org.apache.log4j.Logger.getLogger(ScreenStatus.class);
    /**
     * SceenLock.
     */
    private int state;

    /**
     * Constructor.
     */
    public ScreenStatus() {
        LOGGER.info("ScreenStatus");
        InputStreamReader stream = null;
        try {
            final Process runtime = Runtime.getRuntime().exec("gnome-screensaver-command --query");
            runtime.waitFor();
            stream = new InputStreamReader(runtime.getInputStream());
            final BufferedReader reader = new BufferedReader(stream);
            final String line = reader.readLine();
            if (line != null) {
                LOGGER.info(line);
                if (line.contains("inactive")) {
                    state = 0;
                } else {
                    state = 1;
                }
            }
        } catch (IOException e) {
            LOGGER.fatal(e);
        } catch (InterruptedException e) {
            LOGGER.error(e);
        } finally {
            try {
                stream.close();
            } catch (IOException e) {
                LOGGER.error(e);
            }
        }
    }

    /**
     * Returns the readings generated by the job.
     *
     * @return the readings generated as Message.NodeReadings,
     */
    public final Message.NodeReadings getReadings() {
        final Message.NodeReadings.Builder readings = Message.NodeReadings.newBuilder();

        final Message.NodeReadings.Reading.Builder reading1 = Message.NodeReadings.Reading.newBuilder();
        reading1.setNode(PcMonitor.getPrefix() + PcMonitor.getHostname());
        final StringBuilder capability1 = new StringBuilder()
                .append(PcMonitor.getPrefix())
                .append(CAPABILITY_PREFIX)
                .append("lockScreen");
        reading1.setCapability(capability1.toString());
        reading1.setDoubleReading(state);
        reading1.setTimestamp(System.currentTimeMillis());
        readings.addReading(reading1.build());

        LOGGER.info(reading1.toString());
        return readings.build();
    }

    /**
     * testing main.
     *
     * @param args none.
     */
    public static void main(final String[] args) {
        final ScreenStatus item = new ScreenStatus();
        LOGGER.info(item.getReadings());

    }

}
