package eu.uberdust.pcmonitor.jobs.unix;

import eu.uberdust.communication.protobuf.Message;
import eu.uberdust.pcmonitor.PcMonitor;
import eu.uberdust.pcmonitor.jobs.AbstractJob;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

/**
 * Created by IntelliJ IDEA.
 * User: amaxilatis
 * Date: 3/26/12
 * Time: 9:22 PM
 */
public class ProcessesInfo extends AbstractJob {
    /**
     * LOGGER.
     */
    private static final org.apache.log4j.Logger LOGGER = org.apache.log4j.Logger.getLogger(ProcessesInfo.class);
    /**
     * Tasks on System.
     */
    private int tasks;

    /**
     * Constructor.
     */
    public ProcessesInfo() {
        tasks = 0;

        InputStreamReader stream = null;
        try {
            final Process runtime = Runtime.getRuntime().exec("ps hax | wc -l");
            runtime.waitFor();
            stream = new InputStreamReader(runtime.getInputStream());
            final BufferedReader reader = new BufferedReader(stream);
            final String line = reader.readLine();
            if (line != null) {
                tasks = Integer.parseInt(line);
            }
        } catch (IOException e) {
            LOGGER.fatal(e);
        } catch (InterruptedException e) {
            LOGGER.error(e);
        } finally {
            try {
                stream.close();
            } catch (IOException e) {
                LOGGER.error(e);
            }
        }
    }

    /**
     * Returns the readings generated by the job.
     *
     * @return the readings generated as Message.NodeReadings,
     */
    public final Message.NodeReadings getReadings() {
        LOGGER.info("getReadings");

        final Message.NodeReadings.Builder readings = Message.NodeReadings.newBuilder();

        final Message.NodeReadings.Reading.Builder reading1 = Message.NodeReadings.Reading.newBuilder();
        reading1.setNode(PcMonitor.getPrefix() + PcMonitor.getHostname());
        final StringBuilder capability1 = new StringBuilder()
                .append(PcMonitor.getPrefix())
                .append(CAPABILITY_PREFIX)
                .append("tasks");
        reading1.setCapability(capability1.toString());
        reading1.setDoubleReading(tasks);
        reading1.setTimestamp(System.currentTimeMillis());
        readings.addReading(reading1.build());

        return readings.build();
    }

    /**
     * testing main.
     *
     * @param args none.
     */
    public static void main(final String[] args) {
        final ProcessesInfo item = new ProcessesInfo();
        LOGGER.info(item.getReadings());

    }
}
