package eu.uberdust.pcmonitor.jobs;

import eu.uberdust.communication.protobuf.Message;
import eu.uberdust.network.NetworkManager;
import eu.uberdust.pcmonitor.jobs.unix.disabled.ScreenStatus;
import org.quartz.Job;
import org.quartz.JobExecutionContext;
import org.quartz.JobExecutionException;

import java.io.IOException;

/**
 * Created by IntelliJ IDEA.
 * User: amaxilatis
 * Date: 3/26/12
 * Time: 11:44 PM
 */
public abstract class AbstractJob implements Job {
    /**
     * CapabilityPrefix.
     */
    public static final String CAPABILITY_PREFIX = "node:capability:";
    /**
     * LOGGER.
     */
    private static final org.apache.log4j.Logger LOGGER = org.apache.log4j.Logger.getLogger(ScreenStatus.class);


    /**
     * Returns the readings generated by the job.
     *
     * @return the readings generated as Message.NodeReadings,
     */
    public abstract Message.NodeReadings getReadings();

    @Override
    public void execute(JobExecutionContext jobExecutionContext) throws JobExecutionException {
        LOGGER.info("execute");
        try {
            NetworkManager.getInstance().sendNodeReading(getReadings());
        } catch (IOException e) {
            LOGGER.error(e);
        }
    }

}
